name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "20 5 */1 * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "donnerx1998@gmail.com"
          git config --local user.name "donnerx1998"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "i have a idea"
          git push
